- name: Install any necessary dependency
  apt:
    name: "apt-transport-https"
    state: present
    update_cache: yes
    cache_valid_time: 3600

- name: Import InfluxData GPG signing key
  apt_key:
    url: "{{ influxdb_apt_key_url }}"
    state: present
    id: "0x2582E0C5"

- name: Add InfluxData repository
  apt_repository:
    repo: "{{ influxdb_apt_repo_url }}"
    state: present

- name: Install InfluxDB package
  apt:
    name: influxdb
    state: present
    update_cache: yes
    cache_valid_time: 3600
