# TODO: Use md5sum to check download
- name: Download version
  get_url:
    url: "{{ influxdb_dl_url }}"
    dest: "{{ influxdb_pkg }}"
  tags:
    - influxdb

- name: Install package
  command: "dpkg --skip-same-version -i {{ influxdb_pkg }}"
  register: dpkg_result
  changed_when: "dpkg_result.stdout.startswith('Selecting')"
  when: ansible_distribution in ['Ubuntu', 'Debian']
  tags:
    - influxdb
